name: Master PR

on:
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build
        working-directory: ./BSDetector/
        run: dotnet build --configuration Release
      - name: Test with dotnet
        working-directory: ./BSDetector.Tests/
        run: dotnet test --configuration Release
